// Słownik rymów dla trybu „Wypluj się z rymów".
//
// Osobny od banku poziomów (level-*.json): tam słowa są dobierane pod cue,
// tutaj chodzi o głębię jednej rodziny rymów — żeby po rundzie było co pokazać.
// Format: jeden string na końcówkę, słowa rozdzielone spacją.

const RHYME_WORDS: Record<string, string> = {
  'ość': 'agresywność aktualność aktywność barwność bezbarwność bezczelność bezstronność bezużyteczność biegłość bierność bliskość błyskotliwość brutalność bystrość całość chciwość chorobliwość chytrość ciekawość cielesność ciemność cierpliwość częstotliwość czułość czystość dbałość delikatność długość dojrzałość dokładność domyślność donośność dostępność dowcipność duchowość dwulicowość dziwność elastyczność fałszywość giętkość gładkość głębokość głośność godność gorliwość gospodarność gotowość grubość grzeczność grzeszność gwałtowność hałaśliwość hardość hojność ilość jakość jaskrawość jasność kłamliwość konieczność konkretność kruchość lekkomyślność lekkość litość łagodność łatwość mądrość mglistość miękkość miłość młodość możliwość mściwość naiwność namiętność nerwowość niedbałość niegrzeczność niemożliwość nieobecność nieprzytomność nierealność nieświadomość nietrwałość nieważność niezależność niezwykłość nikczemność normalność nowość obecność obojętność obowiązkowość oczywistość odległość odporność ogólnikowość ospałość ostrość ostrożność oszczędność otwartość oziębłość pewność płynność płytkość podłość pojemność pomocność porywczość powierzchowność powszechność pracowitość prawdomówność prawość prostolinijność próżność przebiegłość przeszłość przezorność przydatność przyjemność przykrość przyszłość przytomność punktualność radosność radość realność rozrzutność roztropność ruchliwość rzadkość rzeczowość rzeczywistość rzetelność samotność schludność serdeczność skromność skuteczność słabość słodkość solidność spokojność sprawiedliwość sprawność srogość stanowczość staranność starość stronniczość sumienność surowość szarość szczelność szczerość szerokość szlachetność szorstkość sztywność śmiałość śmieszność świadomość świeżość świętość tajemniczość tchórzliwość teraźniejszość terminowość troskliwość trudność trwałość twardość uczciwość uczuciowość umiejętność uprzejmość uważność użyteczność wartość ważność wdzięczność wesołość wierność witalność wolność wrażliwość wściekłość wydajność wyjątkowość wyniosłość wyrazistość wyrozumiałość wysokość wytrwałość wytrzymałość zachłanność zaciekłość zależność zapalczywość zapobiegliwość zaradność zawiłość zawziętość zazdrość zdolność zdrowotność złożoność zmysłowość zuchwałość zwyczajność życzliwość żywotność',
  'anie': 'badanie bieganie budowanie bujanie całowanie celowanie chowanie chrapanie chwytanie chybianie czekanie czesanie czytanie danie dorzucanie dotrzymywanie drukowanie dyskutowanie dźwiganie finiszowanie gadanie gotowanie granie gwizdanie hamowanie holowanie huśtanie improwizowanie kichanie kiwanie klaskanie klękanie kochanie kołysanie komponowanie kopanie kopiowanie kupowanie latanie ładowanie łamanie łapanie machanie malowanie mieszanie mieszkanie mijanie miksowanie mruganie nagrywanie naprawianie narzekanie narzucanie notowanie obejmowanie obiecywanie oddalanie oddawanie oddychanie odejmowanie odmawianie odpinanie odpoczywanie odtwarzanie odwiedzanie oglądanie oklaskiwanie opowiadanie opuszczanie otwieranie pakowanie pamiętanie parkowanie pchanie pilnowanie pisanie planowanie płakanie pływanie podkreślanie podlewanie podróżowanie podrzucanie pokazywanie porządkowanie potrząsanie pożyczanie pranie prasowanie próbowanie przegrywanie przesuwanie przyglądanie przyjmowanie przyspieszanie przytulanie pukanie puszczanie pytanie rachowanie ratowanie rąbanie rozbieranie rozdawanie rozdzielanie rozklejanie rozładowywanie rozmawianie rozpalanie rozwiązywanie rysowanie ryzykowanie rzucanie siadanie skakanie skanowanie sklejanie słuchanie sortowanie spacerowanie spajanie spanie spotykanie sprawdzanie sprzątanie sprzedawanie stanie startowanie stawianie strzelanie sumowanie szeptanie szukanie ściganie ścinanie śniadanie śpiewanie tankowanie testowanie trafianie trenowanie trzymanie tupanie ubieranie ubranie uciekanie układanie wdychanie wiązanie wirowanie witanie wklejanie wołanie wpatrywanie wracanie wrzucanie wspominanie wstawanie wybieranie wyglądanie wygrywanie wygwizdywanie wyjaśnianie wymazywanie wypoczywanie wypożyczanie wyprzedzanie wyrzucanie występowanie wzdychanie zaczynanie zaglądanie zakładanie zamykanie zapinanie zapisywanie zapominanie zapraszanie zaznaczanie zbieranie zbliżanie zdanie zdejmowanie zgadzanie ziewanie zmywanie znajdowanie zrywanie zrzucanie zwalnianie zwiedzanie zwracanie żartowanie żegnanie',
  'enie': 'budzenie burzenie chłodzenie chodzenie chwalenie cierpienie ćwiczenie doświadczenie duszenie dzielenie ganienie gaszenie gniecenie golenie karmienie kiszenie klejenie kładzenie kruszenie krzyczenie kwaszenie leczenie lepienie leżenie liczenie łączenie marzenie miażdżenie mielenie mierzenie milczenie mnożenie mówienie mrożenie myślenie niszczenie noszenie nudzenie oczyszczenie odliczenie odnowienie odróżnienie ogłoszenie określenie omówienie opóźnienie orzeczenie ostrzenie ostrzeżenie oświadczenie oświetlenie oznaczenie ożywienie palenie parzenie pieczenie podnoszenie pojenie połączenie położenie pomieszczenie porozumienie poruszenie postanowienie poświęcenie powiedzenie powiększenie powodzenie pozwolenie pragnienie proszenie prześwietlenie przybliżenie przypomnienie przyrzeczenie przyspieszenie robienie rozliczenie rozłączenie rozmieszczenie rozmnożenie rozproszenie rozróżnienie rozświetlenie sadzenie skupienie słodzenie słyszenie smażenie solenie spalenie spełnienie spojrzenie studzenie stwierdzenie suszenie szkolenie tępienie tłumaczenie topienie tuczenie tworzenie ubezpieczenie uczczenie uczenie uderzenie ukojenie ukończenie ulepszenie umieszczenie uniesienie uproszczenie urodzenie uspokojenie ustalenie ustawienie uszkodzenie utrudnienie uwolnienie uzupełnienie warzenie ważenie westchnienie wędzenie widzenie wiercenie wierzenie wnoszenie wrażenie wręczenie wspomnienie wtrącenie wybaczenie wyciszenie wydarzenie wygaszenie wyjaśnienie wykluczenie wykończenie wykroczenie wyleczenie wyliczenie wymierzenie wymówienie wynagrodzenie wyobrażenie wypełnienie wyposażenie wyrażenie wyróżnienie wyświetlenie wytłumaczenie wzmocnienie wzruszenie zabezpieczenie zadowolenie zagrożenie zakażenie zakończenie założenie zamówienie zanieczyszczenie zaokrąglenie zapalenie zapewnienie zapomnienie zaproszenie zaskoczenie zastanowienie zastąpienie zaświadczenie zatrudnienie zawieszenie zbliżenie zdarzenie zdziwienie zgłoszenie zgromadzenie zjednoczenie złagodzenie złączenie zmartwienie zmęczenie zmniejszenie zmuszenie znaczenie zniechęcenie zniszczenie znoszenie znudzenie znużenie zwątpienie zwiększenie zwolnienie żywienie',
  'acja': 'aplikacja edukacja generacja gradacja gratulacja identyfikacja iluminacja imitacja implementacja improwizacja inauguracja indoktrynacja inflacja informacja inicjacja innowacja inspiracja instalacja integracja interpretacja intonacja irygacja izolacja kalkulacja kombinacja kompensacja kompilacja komplikacja komunikacja koncentracja kondensacja konfiguracja konfrontacja koniugacja konsolidacja konsultacja kontemplacja kooperacja koordynacja korelacja kreacja kremacja kultywacja kwalifikacja kwotacja legalizacja legitymacja likwidacja limitacja lokalizacja manifestacja manipulacja medytacja migracja moderacja modernizacja modyfikacja motywacja nawigacja negacja nominacja normalizacja notacja nowelizacja obserwacja okupacja operacja optymalizacja oracja organizacja orientacja oscylacja owacja penetracja perforacja personalizacja plantacja polaryzacja populacja prezentacja prowokacja publikacja racja radiacja realizacja recytacja reformacja regulacja rehabilitacja reinkarnacja rejestracja reklamacja rekomendacja rekrutacja relacja relaksacja renowacja reprezentacja reputacja restauracja rezerwacja rezygnacja rotacja sanacja segregacja sensacja separacja socjalizacja specjalizacja specyfikacja spekulacja stabilizacja stacja stagnacja standaryzacja sterylizacja stymulacja symulacja synchronizacja systematyzacja sytuacja tabulacja transformacja translacja transplantacja uzurpacja wakacja walidacja wariacja wegetacja wentylacja weryfikacja wibracja windykacja wizualizacja wizytacja',
  'ek': 'bębenek brzeżek brzuszek budynek chlebek człowiek czubek czwartek daszek dodatek dołek domek dymek dzbanek dzbanuszek dzwonek ganek garnek garnuszek grzybek guzek kabelek kamyczek kawałek kieliszek kierunek klocek kołek kominek koniuszek korzonek koszyczek kotek krzaczek kubek kwiatek kwiatuszek listeczek listek majątek malunek meldunek młotek mostek nieporządek nosek numerek obrazek ogonek ogórek okruszek ołówek orzeszek pagórek paluszek papierek patyczek piasek piątek piesek placek płotek pocałunek początek podarunek podatek pomidorek poranek porządek proszek przypadek ptaszek pyłek rachunek ranek ratunek rondelek rowerek rymek rysunek schodek serek skrawek słoiczek smyczek soczek spadek statek stołek strzępek supełek szacunek sznurek środek trunek uczynek upadek uszek węgielek węzełek wiaterek wieczorek wierzchołek worek wtorek wyjątek wypadek wzgórek zadatek zamek ząbek znaczek żołądek żwirek',
  'ka': 'aktorka alejka altanka apaszka aptekarka bańka beczka biegaczka bluzka bombka bramka bransoletka broszka budka butelka chmurka choinka chusteczka ciotka czapka deskorolka dolinka drabinka dróżka dziennikarka dziewczynka ekspedientka filiżanka fotka fotografka fryzjerka furtka gazetka górka gumka gwiazdka huśtawka kamizelka kartka kasetka kasjerka kelnerka klamerka klatka klientka kokardka koleżanka kopertówka koronka koszulka kredka kropelka książka kucharka kulka kurtka lalka lampka lekarka linijka ławeczka łączka łódka łyżka malarka marynarka mgiełka modelka monetka motorówka muszelka narciarka nauczycielka nitka opaska paczka pasażerka perełka pielęgniarka piłka piosenkarka pisarka piżamka pływaczka pocztówka podróżniczka poetka polanka policjantka półka prawniczka projektantka przepaska przewodniczka przyjaciółka puszka rakietka ramka rękawiczka rolka rowerzystka rybka rzeczka sąsiadka sekretarka siatka siostrzyczka skakanka skałka skarpetka skrzynka spinka sportsmenka strażaczka strużka studentka sukienka szafka szkatułka szklanka szpulka ścieżka tancerka teczka temperówka tłumaczka torebka turystka uliczka ulotka urzędniczka walizka wędka wiosenka wizytówka wnuczka wrotka wstążka zabawka zawieszka żaglówka',
  'nik': 'bezpiecznik celnik chłodnik cukiernik czajnik czeladnik dłużnik dziennik gołębnik górnik grzejnik grzesznik hurtownik kierownik klucznik kurnik latarnik leśnik licznik łącznik męczennik miesięcznik modlitewnik naczelnik najemnik napastnik następnik notatnik ogrodnik pamiętnik płatnik podatnik podręcznik podróżnik pojemnik pomocnik poprzednik poradnik pracownik prawnik przeciwnik przełącznik przewodnik pustelnik ratownik robotnik rocznik rolnik rytownik rzecznik rzemieślnik rzeźnik skarbnik słownik sojusznik sternik strażnik śmietnik śpiewnik taternik technik tygodnik uczestnik urzędnik wędrownik włącznik wojownik wskaźnik współpracownik wyłącznik zakonnik zawodnik zbiornik zwolennik',
  'arz': 'aptekarz bajarz bednarz betoniarz bibliotekarz blacharz bramkarz brukarz bursztyniarz cmentarz dekarz drukarz dziennikarz farbiarz garbarz garncarz gawędziarz gołębiarz gorzelarz gospodarz grabarz kalendarz kamieniarz kolarz kolejarz kominiarz koniarz koszykarz kotlarz księgarz kucharz kwiaciarz lekarz ludwisarz łyżwiarz malarz marynarz masarz mleczarz młynarz modelarz murarz narciarz owczarz owocarz parkieciarz piekarz piłkarz pisarz posadzkarz pszczelarz puszkarz rusznikarz rymarz rzeźbiarz siatkarz siodlarz stolarz szklarz ślusarz taksówkarz tokarz tramwajarz tynkarz wędliniarz winiarz włodarz zabawkarz zbrojarz zielarz żeglarz',
  'owy': 'atomowy autobusowy balkonowy bananowy bankowy beżowy bitowy blokowy bordowy brzoskwiniowy budżetowy burzowy cebulowy cenowy chmurowy chwilowy cukrowy cyfrowy cytrynowy czekoladowy czosnkowy dachowy deszczowy domowy drogowy drzwiowy dyniowy ekranowy etapowy festiwalowy fiołkowy fotelowy garażowy gazowy głośnikowy godzinowy gotówkowy gruszkowy grzybowy gumowy guzikowy handlowy internetowy jabłkowy jagodowy jądrowy kablowy kanapowy kartonowy klawiszowy klipowy klubowy kolejowy kominowy komputerowy koncertowy korytarzowy kredytowy kremowy krzyżowy księżycowy kwadratowy kwiatowy lampowy laserowy liliowy liniowy lodowy łazienkowy łąkowy łóżkowy makowy malinowy meblowy metalowy mieszkaniowy migdałowy mikrofonowy miodowy morelowy mostowy odcinkowy ogórkowy ogrodowy olejowy oliwkowy orzechowy osiedlowy owocowy paliwowy papierowy parkowy piaskowy pieprzowy pionowy plastikowy plażowy płytowy podatkowy podłogowy pokojowy polowy pomarańczowy pomidorowy poziomowy półkowy prądowy programowy punktowy rakietowy refrenowy rowerowy różowy rymowy rynkowy samochodowy serwerowy sieciowy singlowy słonecznikowy słuchawkowy służbowy sportowy sprzętowy stalowy stołowy stożkowy strychowy sufitowy systemowy szkieletowy śliwkowy śniegowy tekstowy tekturowy tramwajowy trasowy truskawkowy tunelowy tygodniowy walcowy waniliowy warstwowy wersowy węglowy wiatrowy wiekowy wiśniowy zimowy ziołowy zwrotkowy',
  'ony': 'broniony ceniony chroniony doceniony duszony dzielony gaszony karmiony kwaszony leczony lubiony mrożony nachylony nagłośniony nagrodzony nakręcony narzucony nauczony obniżony obudzony obwiniony odkręcony odmieniony ogłoszony ograniczony onieśmielony oskarżony ośmielony ośmieszony oświetlony otworzony ożywiony palony parzony pieczony pochylony pocieszony podłączony podniesiony podwyższony podzielony połączony położony pomniejszony poniżony poruszony postawiony powiększony proszony przechylony przedłużony przekrzywiony przerażony przestawiony przetłumaczony przyciszony przyćmiony przykręcony przyniesiony przyuczony rozbudzony rozdzielony rozgrzeszony rozjaśniony rozkręcony rozłączony rozłożony rozproszony rozszerzony rozświetlony rozzłoszczony skończony skręcony skrócony skupiony słodzony smażony solony strudzony stworzony suszony uchylony ucieszony uciszony uczony ukojony ukręcony ułożony upokorzony uproszczony uspokojony ustawiony uśpiony wędzony wkręcony włączony wrzucony wyciszony wydłużony wyjaśniony wykrzywiony wyłączony wymieniony wynagrodzony wyniesiony wyproszony wyrzucony wytłumaczony wytworzony wyuczony wywyższony wzruszony zachęcony zachwycony zaciemniony zakręcony zakrzywiony zamieniony zaniepokojony zaniesiony zaproszony zarzucony zaskoczony zasłużony zaszczycony zawiedziony zawstydzony zbudzony zburzony zdziwiony zgłoszony zgromadzony zgubiony zjednoczony złożony zmartwiony zmęczony zmieniony zmniejszony znaleziony zniechęcony zniszczony znudzony zrobiony zwiększony żywiony',
};

export type RhymeEnding = string;

/** Endings we consider deep enough to drill for a few minutes. */
export const RHYME_ENDINGS: RhymeEnding[] = Object.keys(RHYME_WORDS)
  .sort((a, b) => a.localeCompare(b, 'pl'));

const cache = new Map<string, string[]>();

/** Every rhyme we know for an ending, alphabetically (Polish collation). */
export function rhymeWords(ending: string): string[] {
  const hit = cache.get(ending);
  if (hit) return hit;
  const words = (RHYME_WORDS[ending] ?? '').split(' ').filter(Boolean);
  cache.set(ending, words);
  return words;
}

export function rhymeCount(ending: string): number {
  return rhymeWords(ending).length;
}

export function randomRhymeEnding(): RhymeEnding {
  return RHYME_ENDINGS[Math.floor(Math.random() * RHYME_ENDINGS.length)];
}
